import { AGNES_MODEL_API_PROFILE_IDS } from '../../../modules/agnesProviderProfiles.js';
function createTextModelApiManifest({
  modelId: _0xa5dac3,
  executionId: _0x2e01ec,
  displayName: _0x4e45d2,
  aliases: aliases = null,
  provider: provider = 'runninghub',
  icon: icon = 'images/RH.png',
  description: description = 'RunningHub image-to-text model API',
  inputSlots: inputSlots = null,
  extensions: extensions = null,
}) {
  const _0x209c35 = {
    schemaVersion: '1.0',
    modelId: _0xa5dac3,
    ...(Array.isArray(aliases) ? { aliases: aliases } : {}),
    provider: provider,
    kind: 'text',
    adapterType: 'modelApi',
    executionId: _0x2e01ec,
    displayName: _0x4e45d2,
    icon: icon,
    description: description,
    inputSlots: Object.freeze(
      inputSlots || {
        allowedKinds: Object.freeze(['image', 'text']),
        minByKind: Object.freeze({ image: 1 }),
        maxByKind: Object.freeze({ image: 8, video: 0, audio: 0 }),
      },
    ),
    uiSchema: Object.freeze({ fields: Object.freeze([]) }),
    async: true,
    cancellable: false,
    outputType: 'text',
  };
  return (
    extensions && typeof extensions === 'object' && (_0x209c35.extensions = Object.freeze(extensions)),
    Object.freeze(_0x209c35)
  );
}
function createRunningHubTextModelApiManifest(_0x40670c) {
  return Object.freeze({
    schemaVersion: '1.0',
    modelId: _0x40670c.modelId,
    provider: 'runninghub',
    kind: 'text',
    adapterType: 'modelApi',
    executionId: _0x40670c.executionId,
    displayName: _0x40670c.displayName,
    icon: 'images/RH.png',
    description: 'RunningHub image-to-text model API',
    inputSlots: Object.freeze({
      allowedKinds: Object.freeze(['image', 'text']),
      minByKind: Object.freeze({ image: 1 }),
      maxByKind: Object.freeze({ image: 8, video: 0, audio: 0 }),
    }),
    uiSchema: Object.freeze({ fields: Object.freeze([]) }),
    ...(_0x40670c.extensions && typeof _0x40670c.extensions === 'object'
      ? { extensions: Object.freeze(_0x40670c.extensions) }
      : {}),
    async: true,
    cancellable: false,
    outputType: 'text',
  });
}
function createTextExecutionManifest({
  id: _0x2a4fc0,
  model: _0x185e2a,
  provider: provider = 'runninghub',
  endpoint: endpoint = '/openapi/v2',
  endpointMode: endpointMode = 'image-to-text',
  bodyMapping: bodyMapping = null,
  responseMapping: responseMapping = null,
  result: result = null,
  extensions: extensions = null,
}) {
  return Object.freeze({
    schemaVersion: '1.0',
    id: _0x2a4fc0,
    provider: provider,
    kind: 'text',
    adapterType: 'modelApi',
    endpoint: endpoint,
    endpointMode: endpointMode,
    method: 'POST',
    model: _0x185e2a,
    ...(extensions && typeof extensions === 'object' ? { extensions: Object.freeze(extensions) } : {}),
    headers: Object.freeze({ 'Content-Type': 'application/json' }),
    bodyMapping: Object.freeze(bodyMapping || { promptField: 'prompt', inputImageField: 'imageUrl' }),
    responseMapping: Object.freeze(
      responseMapping || {
        taskIdPath: 'taskId',
        resultPaths: Object.freeze(['results[].text', 'text', 'output']),
      },
    ),
    result: Object.freeze(
      result || { taskIdPath: 'taskId', textFields: Object.freeze(['text', 'output', 'content']) },
    ),
  });
}
const RUNNINGHUB_IMAGE_TO_TEXT_MODELS = Object.freeze([
    Object.freeze({
      modelId: 'runninghub-model/rhart-text-g-3-flash-preview-cv/image-to-text',
      executionId: 'runninghub.model-api.rhart-text-g-3-flash-cv.v1',
      displayName: 'RunningHub G-3 Flash CV',
      model: 'rhart-text-g-3-flash-preview-cv/image-to-text',
    }),
    Object.freeze({
      modelId: 'runninghub-model/rhart-text-g-3-pro-preview-cv/image-to-text',
      executionId: 'runninghub.model-api.rhart-text-g-3-pro-cv.v1',
      displayName: 'RunningHub G-3 Pro CV',
      model: 'rhart-text-g-3-pro-preview-cv/image-to-text',
    }),
  ]),
  CHAT_COMPLETION_TEXT_INPUT_SLOTS = Object.freeze({
    allowedKinds: Object.freeze(['text', 'image']),
    minByKind: Object.freeze({ text: 0, image: 0 }),
    maxByKind: Object.freeze({ image: 8, video: 0, audio: 0 }),
  }),
  CHAT_COMPLETION_TEXT_IMAGE_VIDEO_INPUT_SLOTS = Object.freeze({
    allowedKinds: Object.freeze(['text', 'image', 'video']),
    minByKind: Object.freeze({ text: 0, image: 0, video: 0 }),
    maxByKind: Object.freeze({ image: 8, video: 3, audio: 0 }),
  }),
  CHAT_COMPLETION_TEXT_ONLY_INPUT_SLOTS = Object.freeze({
    allowedKinds: Object.freeze(['text']),
    minByKind: Object.freeze({ text: 0 }),
    maxByKind: Object.freeze({ image: 0, video: 0, audio: 0 }),
  }),
  RUNNINGHUB_LLM_TEXT_MODELS = Object.freeze([
    Object.freeze({
      modelId: 'qwen/qwen3.6-plus',
      executionId: 'runninghub.model-api.text.qwen3-6-plus.v1',
      displayName: 'Qwen3.6 Plus',
      model: 'qwen/qwen3.6-plus',
      title: 'qwen3.6-plus',
      subtitle: '阿里旗舰模型，支持长上下文与文本推理',
      icon: 'qwen',
      order: 30,
    }),
    Object.freeze({
      modelId: 'qwen/qwen3-vl-235b-a22b-instruct',
      executionId: 'runninghub.model-api.text.qwen3-vl-235b-a22b-instruct.v1',
      displayName: 'Qwen3-VL 235B A22B Instruct',
      model: 'qwen/qwen3-vl-235b-a22b-instruct',
      title: 'qwen3-vl-235b-a22b-instruct',
      subtitle: '视觉语言模型，适合图片识别与图文理解',
      icon: 'qwen',
      inputSlots: CHAT_COMPLETION_TEXT_INPUT_SLOTS,
      order: 40,
    }),
    Object.freeze({
      modelId: 'deepseek/deepseek-v4-flash',
      executionId: 'runninghub.model-api.text.deepseek-v4-flash.v1',
      displayName: 'DeepSeek V4 Flash',
      model: 'deepseek/deepseek-v4-flash',
      title: 'deepseek-v4-flash',
      subtitle: 'DeepSeek V4 快速版，适合高频文本任务',
      icon: 'deepseek',
      order: 50,
    }),
    Object.freeze({
      modelId: 'deepseek/deepseek-v4-pro',
      executionId: 'runninghub.model-api.text.deepseek-v4-pro.v1',
      displayName: 'DeepSeek V4 Pro',
      model: 'deepseek/deepseek-v4-pro',
      title: 'deepseek-v4-pro',
      subtitle: 'DeepSeek V4 专业版，适合复杂推理与代码任务',
      icon: 'deepseek',
      order: 60,
    }),
    Object.freeze({
      modelId: 'bytedance/doubao-seed-2.0-lite',
      executionId: 'runninghub.model-api.text.doubao-seed-2-lite.v1',
      displayName: 'Doubao Seed 2.0 Lite',
      model: 'bytedance/doubao-seed-2.0-lite',
      title: 'doubao-seed-2.0-lite',
      subtitle: '豆包 Seed 2.0 轻量版，适合低成本文本任务',
      icon: 'runninghub',
      order: 70,
    }),
    Object.freeze({
      modelId: 'bytedance/doubao-seed-2.0-pro',
      executionId: 'runninghub.model-api.text.doubao-seed-2-pro.v1',
      displayName: 'Doubao Seed 2.0 Pro',
      model: 'bytedance/doubao-seed-2.0-pro',
      title: 'doubao-seed-2.0-pro',
      subtitle: '豆包 Seed 2.0 旗舰版，适合复杂推理和文本生成',
      icon: 'runninghub',
      order: 80,
    }),
  ]),
  VOLCENGINE_TEXT_MODELS = Object.freeze([
    Object.freeze({
      modelId: 'volcengine/doubao-seed-2-0-pro-260215',
      executionId: 'volcengine.model-api.text.doubao-seed-2-0-pro-260215.v1',
      displayName: 'Doubao Seed 2.0 Pro',
      model: 'doubao-seed-2-0-pro-260215',
      title: 'doubao-seed-2-0-pro-260215',
      subtitle: '火山方舟 Doubao Seed 2.0 Pro，适合复杂文本生成与推理',
      icon: 'volcengine',
      order: 10,
    }),
    Object.freeze({
      modelId: 'volcengine/doubao-seed-2-0-mini-260428',
      executionId: 'volcengine.model-api.text.doubao-seed-2-0-mini-260428.v1',
      displayName: 'Doubao Seed 2.0 Mini',
      model: 'doubao-seed-2-0-mini-260428',
      title: 'doubao-seed-2-0-mini-260428',
      subtitle: '火山方舟 Doubao Seed 2.0 Mini，平衡效果与响应速度',
      icon: 'volcengine',
      order: 20,
    }),
    Object.freeze({
      modelId: 'volcengine/doubao-seed-2-0-lite-260428',
      executionId: 'volcengine.model-api.text.doubao-seed-2-0-lite-260428.v1',
      displayName: 'Doubao Seed 2.0 Lite',
      model: 'doubao-seed-2-0-lite-260428',
      title: 'doubao-seed-2-0-lite-260428',
      subtitle: '火山方舟 Doubao Seed 2.0 Lite，适合高频文本任务',
      icon: 'volcengine',
      order: 30,
    }),
  ]),
  // Agnes 2.0 Flash is deprecated by the vendor and no longer returns content, so it is not
  // offered any more. Verified against both lines with live keys.
  AGNES_TEXT_MODELS = Object.freeze([
    Object.freeze({
      modelId: 'agnes/agnes-2.5-flash',
      executionId: 'agnes.model-api.text.agnes-2-5-flash.v1',
      displayName: 'Agnes 2.5 Flash',
      model: 'agnes-2.5-flash',
      title: 'Agnes 2.5 Flash',
      subtitle: 'Agnes AI fast text generation model',
      icon: 'agnes',
      order: 20,
    }),
    Object.freeze({
      modelId: 'agnes/agnes-3.0-flash',
      executionId: 'agnes.model-api.text.agnes-3-0-flash.v1',
      displayName: 'Agnes 3.0 Flash',
      model: 'agnes-3.0-flash',
      title: 'Agnes 3.0 Flash',
      subtitle: 'Agnes AI fast text generation model',
      icon: 'agnes',
      order: 30,
    }),
  ]),
  CHAT_COMPLETION_TEXT_RESPONSE_MAPPING = Object.freeze({
    resultPaths: Object.freeze(['choices[].message.content', 'choices[].delta.content', 'text', 'output']),
  }),
  VOLCENGINE_RESPONSES_TEXT_RESPONSE_MAPPING = Object.freeze({
    resultPaths: Object.freeze([
      'output_text',
      'data.output_text',
      'output[].content[].text',
      'output[].content[].content',
      'data.output[].content[].text',
      'data.output[].content[].content',
      'text',
      'output',
    ]),
  }),
  APIMART_TEXT_RESULT = Object.freeze({
    textFields: Object.freeze(['choices[].message.content', 'text', 'output']),
  }),
  APIMART_TEXT_EXECUTION_EXTENSIONS = Object.freeze({ chatCompletionInputPolicy: 'image-only' }),
  VOLCENGINE_TEXT_EXECUTION_EXTENSIONS = Object.freeze({
    chatCompletionInputPolicy: 'image-video',
    volcengineFiles: Object.freeze({ videoFps: 0.3 }),
  }),
  AGNES_TEXT_EXECUTION_EXTENSIONS = Object.freeze({ chatCompletionInputPolicy: 'image-only' }),
  RUNNINGHUB_LLM_TEXT_EXECUTION_EXTENSIONS = Object.freeze({
    endpointResolver: 'runninghubLlmChatEndpoint',
    chatCompletionInputPolicy: 'image-only',
  }),
  GRSAI_TEXT_MODELS = Object.freeze([
    Object.freeze({
      modelId: 'gemini-3.1-pro',
      executionId: 'grsai.model-api.text.gemini-3-1-pro.v1',
      displayName: 'gemini-3.1-pro',
      model: 'gemini-3.1-pro',
      subtitle: '谷歌最新模型gemini3.1',
      icon: 'grsai',
      order: 10,
    }),
    Object.freeze({
      modelId: 'gemini-3-pro',
      executionId: 'grsai.model-api.text.gemini-3-pro.v1',
      displayName: 'gemini-3-pro',
      model: 'gemini-3-pro',
      subtitle: '谷歌最新模型gemini3.1',
      icon: 'grsai',
      order: 20,
    }),
    Object.freeze({
      modelId: 'gpt-5.4',
      executionId: 'grsai.model-api.text.gpt-5-4.v1',
      displayName: 'gpt-5.4',
      model: 'gpt-5.4',
      subtitle: 'GRSAI chat completion model API',
      icon: 'grsai',
      order: 30,
    }),
    Object.freeze({
      modelId: 'gpt-5.5',
      executionId: 'grsai.model-api.text.gpt-5-5.v1',
      displayName: 'gpt-5.5',
      model: 'gpt-5.5',
      subtitle: 'GRSAI chat completion model API',
      icon: 'grsai',
      order: 40,
    }),
    Object.freeze({
      modelId: 'gemini-3.5-flash',
      executionId: 'grsai.model-api.text.gemini-3-5-flash.v1',
      displayName: 'gemini-3.5-flash',
      model: 'gemini-3.5-flash',
      subtitle: 'GRSAI chat completion model API',
      icon: 'grsai',
      order: 50,
    }),
  ]),
  PPIO_TEXT_MODELS = Object.freeze([
    Object.freeze({
      modelId: 'minimax/minimax-m2.5-highspeed',
      executionId: 'ppio.model-api.text.minimax-m2-5-highspeed.v1',
      displayName: 'MiniMax M2.5-highspeed',
      model: 'minimax/minimax-m2.5-highspeed',
      title: 'minimax-m2.5-highspeed',
      subtitle: '更低延迟、更高性价比的领先模型',
      icon: 'ppio',
      order: 10,
    }),
    Object.freeze({
      modelId: 'qwen/qwen3.5-397b-a17b',
      executionId: 'ppio.model-api.text.qwen3-5-397b-a17b.v1',
      displayName: 'Qwen3.5-397B-A17B',
      model: 'qwen/qwen3.5-397b-a17b',
      title: 'qwen3.5-397b',
      subtitle: '阿里最强开源模型Qwen2.5',
      icon: 'qwen',
      order: 20,
    }),
    Object.freeze({
      modelId: 'deepseek/deepseek-v3.2',
      executionId: 'ppio.model-api.text.deepseek-v3-2.v1',
      displayName: 'DeepSeek-V3.2',
      model: 'deepseek/deepseek-v3.2',
      title: 'deepseek-v3',
      subtitle: '面向未来的新一代大模型',
      icon: 'deepseek',
      order: 30,
    }),
    Object.freeze({
      modelId: 'moonshotai/kimi-k2.5',
      executionId: 'ppio.model-api.text.kimi-k2-5.v1',
      displayName: 'Kimi K2.5',
      model: 'moonshotai/kimi-k2.5',
      title: 'kimi-k2.5',
      subtitle: '月之暗面最新版，超长上下文',
      icon: 'moonshot',
      order: 40,
    }),
  ]),
  APIMART_TEXT_MODELS = Object.freeze([
    Object.freeze({
      modelId: 'apimart/kimi-k2-instruct',
      executionId: 'apimart.model-api.text.kimi-k2-instruct.v1',
      displayName: 'Kimi K2 Instruct',
      model: 'kimi-k2-instruct',
      subtitle: 'APIMart text model',
      order: 10,
    }),
    Object.freeze({
      modelId: 'apimart/deepseek-v4-pro',
      executionId: 'apimart.model-api.text.deepseek-v4-pro.v1',
      displayName: 'DeepSeek V4 Pro',
      model: 'deepseek-v4-pro',
      subtitle: 'APIMart text model',
      order: 20,
    }),
    Object.freeze({
      modelId: 'apimart/deepseek-v4-flash',
      executionId: 'apimart.model-api.text.deepseek-v4-flash.v1',
      displayName: 'DeepSeek V4 Flash',
      model: 'deepseek-v4-flash',
      subtitle: 'APIMart text model',
      order: 30,
    }),
    Object.freeze({
      modelId: 'apimart/gpt-5.5',
      executionId: 'apimart.model-api.text.gpt-5-5.v1',
      displayName: 'GPT-5.5',
      model: 'gpt-5.5',
      subtitle: 'OpenAI-compatible text model',
      order: 40,
    }),
    Object.freeze({
      modelId: 'apimart/gpt-5.4-mini',
      executionId: 'apimart.model-api.text.gpt-5-4-mini.v1',
      displayName: 'GPT-5.4 Mini',
      model: 'gpt-5.4-mini',
      subtitle: 'OpenAI-compatible text model',
      order: 50,
    }),
    Object.freeze({
      modelId: 'apimart/gpt-5.4',
      executionId: 'apimart.model-api.text.gpt-5-4.v1',
      displayName: 'GPT-5.4',
      model: 'gpt-5.4-apimart',
      title: 'gpt-5.4',
      subtitle: '极致逻辑与推理性能，OpenAI 巅峰之作',
      order: 55,
    }),
    Object.freeze({
      modelId: 'apimart/gemini-3.1-pro-preview',
      executionId: 'apimart.model-api.text.gemini-3-1-pro-preview.v1',
      displayName: 'Gemini 3.1 Pro Preview',
      model: 'gemini-3.1-pro-preview',
      title: 'gemini-3.1-pro-preview',
      subtitle: '旗舰级多模态模型，支持超长文本与深度分析',
      icon: 'gemini',
      order: 56,
    }),
    Object.freeze({
      modelId: 'apimart/gemini-3-flash-preview-nothinking',
      executionId: 'apimart.model-api.text.gemini-3-flash-nothinking.v1',
      displayName: 'Gemini 3 Flash',
      model: 'gemini-3-flash-preview-nothinking',
      title: 'gemini-3-flash-preview-nothinking',
      subtitle: '闪电级响应速度，适用于高频率对话与实时任务',
      icon: 'gemini',
      order: 57,
    }),
    Object.freeze({
      modelId: 'apimart/gemini-3.5-flash',
      executionId: 'apimart.model-api.text.gemini-3-5-flash.v1',
      displayName: 'Gemini 3.5 Flash',
      model: 'gemini-3.5-flash',
      title: 'gemini-3.5-flash',
      subtitle: 'APIMart Gemini flash text model',
      icon: 'gemini',
      order: 58,
    }),
    Object.freeze({
      modelId: 'apimart/glm-5.1',
      executionId: 'apimart.model-api.text.glm-5-1.v1',
      displayName: 'GLM-5.1',
      model: 'glm-5.1',
      subtitle: 'APIMart text model',
      order: 60,
    }),
  ]);
export const vendorTextModelApiModelManifests = Object.freeze([
  ...RUNNINGHUB_IMAGE_TO_TEXT_MODELS.map((_0xc06098) =>
    createRunningHubTextModelApiManifest({
      modelId: _0xc06098.modelId,
      executionId: _0xc06098.executionId,
      displayName: _0xc06098.displayName,
      extensions: Object.freeze({
        textMenu: Object.freeze({
          group: 'runninghub',
          order: _0xc06098.modelId.includes('flash') ? 10 : 20,
          title: _0xc06098.modelId.includes('flash') ? 'gemini3-flash' : 'gemini3-pro',
          subtitle: _0xc06098.modelId.includes('flash')
            ? '闪电级响应速度，适用于高频率对话与实时任务'
            : '旗舰级多模态模型，支持超长文本与深度分析',
          icon: 'gemini',
        }),
      }),
    }),
  ),
  ...RUNNINGHUB_LLM_TEXT_MODELS.map((_0x855a94) =>
    createTextModelApiManifest({
      modelId: _0x855a94.modelId,
      executionId: _0x855a94.executionId,
      displayName: _0x855a94.displayName,
      provider: 'runninghub',
      icon: 'images/RH.png',
      description: 'RunningHub LLM chat completion model API',
      inputSlots: _0x855a94.inputSlots || CHAT_COMPLETION_TEXT_ONLY_INPUT_SLOTS,
      extensions: Object.freeze({
        textMenu: Object.freeze({
          group: 'runninghub',
          order: _0x855a94.order,
          title: _0x855a94.title || _0x855a94.displayName,
          subtitle: _0x855a94.subtitle,
          icon: _0x855a94.icon,
        }),
      }),
    }),
  ),
  ...VOLCENGINE_TEXT_MODELS.map((_0x2bc041) =>
    createTextModelApiManifest({
      modelId: _0x2bc041.modelId,
      executionId: _0x2bc041.executionId,
      displayName: _0x2bc041.displayName,
      aliases: Object.freeze([_0x2bc041.model]),
      provider: 'volcengine',
      icon: 'images/volcengine.svg',
      description: 'Volcengine Ark chat completion model API',
      inputSlots: CHAT_COMPLETION_TEXT_IMAGE_VIDEO_INPUT_SLOTS,
      extensions: Object.freeze({
        textMenu: Object.freeze({
          group: 'volcengine',
          order: _0x2bc041.order,
          title: _0x2bc041.title || _0x2bc041.displayName,
          subtitle: _0x2bc041.subtitle,
          icon: _0x2bc041.icon,
        }),
      }),
    }),
  ),
  ...GRSAI_TEXT_MODELS.map((_0x53706d) =>
    createTextModelApiManifest({
      modelId: _0x53706d.modelId,
      executionId: _0x53706d.executionId,
      displayName: _0x53706d.displayName,
      provider: 'grsai',
      icon: 'images/grsai.png',
      description: 'GRSAI chat completion model API',
      inputSlots: CHAT_COMPLETION_TEXT_INPUT_SLOTS,
      extensions: Object.freeze({
        textMenu: Object.freeze({
          group: 'grsai',
          order: _0x53706d.order,
          title: _0x53706d.title || _0x53706d.displayName,
          subtitle: _0x53706d.subtitle,
          icon: _0x53706d.icon,
        }),
      }),
    }),
  ),
  ...PPIO_TEXT_MODELS.map((_0x5f4ceb) =>
    createTextModelApiManifest({
      modelId: _0x5f4ceb.modelId,
      executionId: _0x5f4ceb.executionId,
      displayName: _0x5f4ceb.displayName,
      provider: 'ppio',
      icon: 'images/ppio.png',
      description: 'PPIO chat completion model API',
      inputSlots: CHAT_COMPLETION_TEXT_INPUT_SLOTS,
      extensions: Object.freeze({
        textMenu: Object.freeze({
          group: 'ppio',
          order: _0x5f4ceb.order,
          title: _0x5f4ceb.title || _0x5f4ceb.displayName,
          subtitle: _0x5f4ceb.subtitle,
          icon: _0x5f4ceb.icon,
        }),
      }),
    }),
  ),
  ...APIMART_TEXT_MODELS.map((_0x12f984) =>
    createTextModelApiManifest({
      modelId: _0x12f984.modelId,
      executionId: _0x12f984.executionId,
      displayName: _0x12f984.displayName,
      aliases: _0x12f984.aliases,
      provider: 'apimart',
      icon: 'AM',
      description: 'APIMart chat completion model API',
      inputSlots: CHAT_COMPLETION_TEXT_INPUT_SLOTS,
      extensions: Object.freeze({
        textMenu: Object.freeze({
          group: 'apimart',
          order: _0x12f984.order,
          title: _0x12f984.title || _0x12f984.displayName,
          subtitle: _0x12f984.subtitle,
          ...(_0x12f984.icon ? { icon: _0x12f984.icon } : {}),
        }),
      }),
    }),
  ),
  ...AGNES_TEXT_MODELS.map((_0x2572a5) =>
    createTextModelApiManifest({
      modelId: _0x2572a5.modelId,
      executionId: _0x2572a5.executionId,
      displayName: _0x2572a5.displayName,
      provider: 'agnes',
      icon: 'AG',
      description: 'Agnes AI chat completion model API',
      inputSlots: CHAT_COMPLETION_TEXT_INPUT_SLOTS,
      extensions: Object.freeze({
        // Declares the domestic and international lines so the key panel can offer the route
        // switch. Without it Agnes showed no route selector at all.
        providerProfiles: AGNES_MODEL_API_PROFILE_IDS,
        textMenu: Object.freeze({
          group: 'agnes',
          order: _0x2572a5.order,
          title: _0x2572a5.title || _0x2572a5.displayName,
          subtitle: _0x2572a5.subtitle,
          icon: _0x2572a5.icon,
        }),
      }),
    }),
  ),
]);
export const vendorTextModelApiExecutionManifests = Object.freeze([
  ...RUNNINGHUB_IMAGE_TO_TEXT_MODELS.map((_0x2610be) =>
    createTextExecutionManifest({ id: _0x2610be.executionId, model: _0x2610be.model }),
  ),
  ...RUNNINGHUB_LLM_TEXT_MODELS.map((_0x295ad9) =>
    createTextExecutionManifest({
      id: _0x295ad9.executionId,
      provider: 'runninghub',
      model: _0x295ad9.model,
      endpoint: '/v1/chat/completions',
      endpointMode: 'chat-completion',
      bodyMapping: Object.freeze({ modelField: 'model', messagesField: 'messages' }),
      responseMapping: CHAT_COMPLETION_TEXT_RESPONSE_MAPPING,
      result: APIMART_TEXT_RESULT,
      extensions: RUNNINGHUB_LLM_TEXT_EXECUTION_EXTENSIONS,
    }),
  ),
  ...VOLCENGINE_TEXT_MODELS.map((_0x458f21) =>
    createTextExecutionManifest({
      id: _0x458f21.executionId,
      provider: 'volcengine',
      model: _0x458f21.model,
      endpoint: '/responses',
      endpointMode: 'responses',
      bodyMapping: Object.freeze({ modelField: 'model', inputField: 'input' }),
      responseMapping: VOLCENGINE_RESPONSES_TEXT_RESPONSE_MAPPING,
      result: APIMART_TEXT_RESULT,
      extensions: VOLCENGINE_TEXT_EXECUTION_EXTENSIONS,
    }),
  ),
  ...GRSAI_TEXT_MODELS.map((_0x1ccf9b) =>
    createTextExecutionManifest({
      id: _0x1ccf9b.executionId,
      provider: 'grsai',
      model: _0x1ccf9b.model,
      endpoint: '/v1',
      endpointMode: 'chat-completion',
      bodyMapping: Object.freeze({ modelField: 'model', messagesField: 'messages' }),
      responseMapping: CHAT_COMPLETION_TEXT_RESPONSE_MAPPING,
      result: APIMART_TEXT_RESULT,
    }),
  ),
  ...PPIO_TEXT_MODELS.map((_0x3a94e1) =>
    createTextExecutionManifest({
      id: _0x3a94e1.executionId,
      provider: 'ppio',
      model: _0x3a94e1.model,
      endpoint: '/openai/v1',
      endpointMode: 'chat-completion',
      bodyMapping: Object.freeze({ modelField: 'model', messagesField: 'messages' }),
      responseMapping: CHAT_COMPLETION_TEXT_RESPONSE_MAPPING,
      result: APIMART_TEXT_RESULT,
    }),
  ),
  ...APIMART_TEXT_MODELS.map((_0x5bb549) =>
    createTextExecutionManifest({
      id: _0x5bb549.executionId,
      provider: 'apimart',
      model: _0x5bb549.model,
      endpoint: '/v1/chat/completions',
      endpointMode: 'chat-completion',
      bodyMapping: Object.freeze({ modelField: 'model', messagesField: 'messages' }),
      responseMapping: CHAT_COMPLETION_TEXT_RESPONSE_MAPPING,
      result: APIMART_TEXT_RESULT,
      extensions: APIMART_TEXT_EXECUTION_EXTENSIONS,
    }),
  ),
  ...AGNES_TEXT_MODELS.map((_0x5cb6e2) =>
    createTextExecutionManifest({
      id: _0x5cb6e2.executionId,
      provider: 'agnes',
      model: _0x5cb6e2.model,
      endpoint: '/v1/chat/completions',
      endpointMode: 'chat-completion',
      bodyMapping: Object.freeze({ modelField: 'model', messagesField: 'messages' }),
      responseMapping: CHAT_COMPLETION_TEXT_RESPONSE_MAPPING,
      result: APIMART_TEXT_RESULT,
      extensions: AGNES_TEXT_EXECUTION_EXTENSIONS,
    }),
  ),
]);
