const path = require('node:path');

module.exports = {
  appId: 'com.aicanvaspro.editor',
  productName: 'updream canvas',
  copyright: 'Copyright (c) 2026 updream canvas',
  asar: false,
  afterSign: path.join(__dirname, 'build', 'write-install-manifest.cjs'),
  directories: {
    output: 'dist-win',
  },
  files: [
    'api/**/*',
    'assets/**/*',
    'backend/**/*',
    'db/**/*',
    'electron/**/*',
    'images/**/*',
    'native/**/*',
    'src/**/*',
    'styles/**/*',
    'vendor/**/*',
    'index.html',
    'style.css',
    'main.js',
    'server.py',
    'requirements.txt',
    'release_notes.txt',
    'package.json',
    '!**/*.test.js',
    '!**/*.test.mjs',
    '!**/*.spec.js',
    '!**/*.map',
    '!**/*.pyc',
    '!**/test_*.py',
    '!**/__pycache__/**',
    '!**/tests/**',
    '!**/test-results/**',
    '!**/playwright-report/**',
  ],
  extraResources: [
    {
      from: '.electron-runtime/runtime',
      to: 'runtime',
    },
  ],
  win: {
    target: [
      { target: 'nsis', arch: ['x64'] },
      { target: 'zip', arch: ['x64'] },
    ],
    icon: path.join(__dirname, 'build', 'app-icon.ico'),
    requestedExecutionLevel: 'asInvoker',
    artifactName: 'updream-canvas-${version}-win-${arch}.${ext}',
  },
  nsis: {
    oneClick: false,
    perMachine: false,
    allowToChangeInstallationDirectory: true,
    createDesktopShortcut: true,
    createStartMenuShortcut: true,
    shortcutName: 'updream canvas',
    include: path.join(__dirname, 'build', 'installer.nsh'),
    artifactName: 'updream-canvas-Setup-${version}-${arch}.${ext}',
  },
};
