import { test } from 'node:test';
import assert from 'node:assert/strict';

import { createCanvasProjectSaveController } from './canvasProjectSaveController.js';

function createController(overrides = {}) {
  const calls = {
    toasts: [],
    loading: [],
  };
  const manager = overrides.manager || {
    _canvases: [],
    getCanvasProjectContext: () => ({ projectId: 'project-1' }),
    captureCanvasSaveCheckpoint: () => ({}),
  };
  const controller = createCanvasProjectSaveController({
    windowObject: {
      CanvasTabManager: manager,
      showGlobalLoading: () => calls.loading.push('show'),
      hideGlobalLoading: () => calls.loading.push('hide'),
    },
    getRoot: () => ({ style: {} }),
    getProjectPackageExportSource:
      overrides.getProjectPackageExportSource ||
      (() => ({
        projectName: 'Project',
        multiData: { canvases: [], activeCanvasId: '' },
      })),
    getActiveCanvasProjectContext: () => ({ projectId: 'project-1' }),
    getCurrentProjectName: overrides.getCurrentProjectName || (() => 'Project'),
    buildProjectContextFromLoadResult: (value) => value,
    reconcileProjectSessionAfterSave: async () => {},
    playProjectSaveAbsorb: () => {},
    fetchProjects: async () => {},
    openSaveDialog: overrides.openSaveDialog || (() => Promise.resolve(false)),
    getShortcutSaveProjectName: overrides.getShortcutSaveProjectName || (() => 'Project'),
    isAutoGeneratedProjectName: overrides.isAutoGeneratedProjectName || (() => false),
    projectNameExistsInProjectList: overrides.projectNameExistsInProjectList || (async () => true),
    showToast: (...args) => calls.toasts.push(args),
  });
  return { controller, calls, manager };
}

test('canvasProjectSaveController: exposes the save, save-as, and shortcut entry points', () => {
  const { controller } = createController();
  assert.deepEqual(Object.keys(controller).sort(), [
    'saveCurrentProjectFromShortcut',
    'saveProject',
    'saveProjectAsLocal',
  ]);
});

test('canvasProjectSaveController: blocks saves for read-only project access contexts', async () => {
  const { controller, calls } = createController({
    getProjectPackageExportSource: () => ({
      projectName: 'Project',
      multiData: {
        canvases: [{ id: 'canvas-1', projectAccess: { canSave: false, saveMessage: '只读项目' } }],
      },
    }),
  });

  assert.equal(await controller.saveCurrentProjectFromShortcut({ waitForDialog: true }), false);
  assert.deepEqual(calls.toasts, [['只读项目', 'warn']]);
});

test('canvasProjectSaveController: opens the naming dialog for unnamed projects', async () => {
  let dialogCalls = 0;
  const { controller, calls } = createController({
    getShortcutSaveProjectName: () => '',
    openSaveDialog: async () => {
      dialogCalls += 1;
      return true;
    },
  });

  assert.equal(await controller.saveCurrentProjectFromShortcut({ waitForDialog: true }), true);
  assert.equal(dialogCalls, 1);
  assert.equal(calls.toasts.length, 0);
});

test('canvasProjectSaveController: opens the naming dialog when the current project name is not in the list', async () => {
  let dialogCalls = 0;
  const { controller } = createController({
    manager: {
      _activeId: '',
      _canvases: [],
      getCanvasProjectContext: () => ({ projectId: 'project-1' }),
      captureCanvasSaveCheckpoint: () => ({}),
    },
    projectNameExistsInProjectList: async () => false,
    openSaveDialog: async () => {
      dialogCalls += 1;
      return true;
    },
  });

  assert.equal(await controller.saveCurrentProjectFromShortcut({ waitForDialog: true }), true);
  assert.equal(dialogCalls, 1);
});

test('canvasProjectSaveController: reports project-list validation failures', async () => {
  const { controller, calls } = createController({
    projectNameExistsInProjectList: async () => {
      throw new Error('list unavailable');
    },
  });

  assert.equal(await controller.saveCurrentProjectFromShortcut({ waitForDialog: true }), false);
  assert.equal(calls.toasts.length, 1);
  assert.equal(calls.toasts[0][1], 'error');
});

test('canvasProjectSaveController: save-as cancellation still releases loading state', async () => {
  const previousWindow = globalThis.window;
  globalThis.window = {
    electronAPI: {
      project: {
        save: async () => ({ canceled: true }),
      },
    },
  };
  try {
    const { controller, calls } = createController({
      getProjectPackageExportSource: () => ({
        projectName: 'Project',
        multiData: { canvases: [], activeCanvasId: 'canvas-1' },
      }),
    });

    await controller.saveProjectAsLocal();
    assert.deepEqual(calls.loading, ['show', 'hide']);
    assert.equal(calls.toasts.length, 0);
  } finally {
    globalThis.window = previousWindow;
  }
});
