import * as project from './project.js';
import { saveDesktopProject } from '../services/desktopProjectService.js';
import { t } from '../i18n/index.js';
import {
  captureCanvasProjectSaveTransaction,
  commitCanvasProjectSave,
  releaseCanvasProjectSave,
} from './canvasProjectSaveTransaction.js';
import { createWorkspacePersistencePresentation } from './workspacePersistencePresentation.js';
import { assertCanvasProjectSaveAllowed } from '../services/canvasProjectAccess.js';
const projectDropdownText = (value, item = {}) => t('projectDropdown.' + value, item);
export function createCanvasProjectSaveController({
  windowObject: windowObject = globalThis['window'],
  getRoot: getRoot,
  getProjectPackageExportSource: getProjectPackageExportSource,
  getActiveCanvasProjectContext: getActiveCanvasProjectContext,
  getCurrentProjectName: getCurrentProjectName,
  buildProjectContextFromLoadResult: buildProjectContextFromLoadResult,
  reconcileProjectSessionAfterSave: reconcileProjectSessionAfterSave,
  playProjectSaveAbsorb: playProjectSaveAbsorb,
  fetchProjects: fetchProjects,
  openSaveDialog: openSaveDialog,
  getShortcutSaveProjectName: getShortcutSaveProjectName,
  isAutoGeneratedProjectName: isAutoGeneratedProjectName,
  projectNameExistsInProjectList: projectNameExistsInProjectList,
  showToast: showToast,
} = {}) {
  const manager = windowObject,
    workspacePersistencePresentation = createWorkspacePersistencePresentation({ getRoot: getRoot });
  let enabled = 0;
  const run = () => {
    return (
      (enabled += 1),
      workspacePersistencePresentation['update']({ status: 'saving' }),
      () => {
        enabled -= 1;
        if (!enabled) workspacePersistencePresentation['update']({ status: 'saved' });
      }
    );
  };
  async function saveProjectAsLocal(options = {}) {
    let captureCanvasProjectSaveTransaction2;
    try {
      const exportSource = getProjectPackageExportSource(options);
      ((captureCanvasProjectSaveTransaction2 = captureCanvasProjectSaveTransaction({
        manager: manager['CanvasTabManager'],
        exportSource: exportSource,
        projectContext: getActiveCanvasProjectContext(),
      })),
        manager['showGlobalLoading']?.(projectDropdownText('savingLocal')));
      const { projectContext: projectContext } = captureCanvasProjectSaveTransaction2,
        filename = await saveDesktopProject(
          exportSource['projectName'] || getCurrentProjectName(),
          exportSource['multiData'],
          { mode: 'saveAs', projectId: projectContext['projectId'], recentId: projectContext['recentId'] },
        );
      if (!filename || filename['canceled']) return;
      (commitCanvasProjectSave(
        captureCanvasProjectSaveTransaction2,
        buildProjectContextFromLoadResult(filename, {
          ...projectContext,
          projectName: exportSource['projectName'],
        }),
      ),
        showToast(projectDropdownText('saveAsSucceeded', { filename: filename['filename'] })),
        fetchProjects());
    } catch (error) {
      if (error?.['code'] !== 'PROJECT_SAVE_FORBIDDEN')
        console['error']('[desktopProject] saveAs failed:', error);
      showToast(
        error?.['message'] || projectDropdownText('saveAsFailed'),
        error?.['code'] === 'PROJECT_SAVE_FORBIDDEN' ? 'warn' : 'error',
      );
    } finally {
      releaseCanvasProjectSave(captureCanvasProjectSaveTransaction2);
      if (manager['hideGlobalLoading']) manager['hideGlobalLoading']();
    }
  }
  function run2(projectName, rename = {}) {
    return captureCanvasProjectSaveTransaction({
      manager: manager['CanvasTabManager'],
      exportSource: getProjectPackageExportSource({ ...rename, projectName: projectName }),
      projectContext: getActiveCanvasProjectContext(),
      rename: rename['renameActiveCanvas'] === !![],
    });
  }
  async function saveProject(projectName2, rename2 = {}, key = null) {
    let run3 = () => {};
    try {
      ((key ||= run2(projectName2, rename2)), (run3 = run()));
      const { exportSource: exportSource2, canvasId: canvasId, projectContext: projectContext2 } = key,
        index = projectContext2['projectId'],
        projectId =
          rename2['saveAs'] === !![] || projectContext2['isTemporary']
            ? projectName2
            : projectContext2['projectId'] || projectName2,
        filename2 = await project['saveProject'](projectId, exportSource2['multiData']);
      if (filename2?.['canceled']) return ![];
      if (!filename2?.['success']) throw new Error(projectDropdownText('saveFailed'));
      if (filename2['success']) {
        const commitCanvasProjectSave2 = commitCanvasProjectSave(
          key,
          buildProjectContextFromLoadResult(filename2, {
            ...projectContext2,
            projectId: projectId,
            projectName: projectName2,
            filename: filename2['filename'],
            recentId: '',
            displayPath: '',
            lastModified: 0,
          }),
          { rename: rename2['renameActiveCanvas'] === !![] },
        );
        return (
          manager['CanvasTabManager']?.['_activeId'] === canvasId &&
            (await reconcileProjectSessionAfterSave(index)),
          playProjectSaveAbsorb(),
          showToast(projectDropdownText('saveSucceeded', { name: projectName2 })),
          await fetchProjects(),
          commitCanvasProjectSave2
        );
      }
    } catch (error2) {
      if (error2?.['code'] !== 'PROJECT_SAVE_FORBIDDEN')
        console['error']('[saveProject] JSON 保存失败:', error2);
      return (
        showToast(
          error2?.['code'] === 'PROJECT_SAVE_FORBIDDEN'
            ? error2['message']
            : projectDropdownText('saveFailed'),
          error2?.['code'] === 'PROJECT_SAVE_FORBIDDEN' ? 'warn' : 'error',
        ),
        ![]
      );
    } finally {
      (releaseCanvasProjectSave(key), run3());
    }
  }
  async function saveCurrentProjectFromShortcut({ waitForDialog: waitForDialog = ![] } = {}) {
    try {
      assertCanvasProjectSaveAllowed(
        getProjectPackageExportSource()['multiData'],
        manager['CanvasTabManager'],
      );
    } catch (error3) {
      return (showToast(error3['message'], 'warn'), ![]);
    }
    const defaultName = getShortcutSaveProjectName();
    if (!defaultName || isAutoGeneratedProjectName(defaultName)) {
      const result = openSaveDialog({ defaultName: defaultName });
      return waitForDialog ? (await result) === !![] : ![];
    }
    const data = run2(defaultName),
      handler = run();
    try {
      let enabled2 = ![];
      try {
        enabled2 = await projectNameExistsInProjectList(defaultName);
      } catch (target) {
        return (
          console['error']('[saveCurrentProjectFromShortcut] 项目列表校验失败:', target),
          showToast(projectDropdownText('listLoadFailed'), 'error'),
          ![]
        );
      }
      if (!enabled2) {
        if (manager['CanvasTabManager']?.['_activeId'] !== data['canvasId']) return ![];
        const source = openSaveDialog({ defaultName: defaultName });
        return waitForDialog ? (await source) === !![] : ![];
      }
      return await saveProject(defaultName, {}, data);
    } finally {
      (releaseCanvasProjectSave(data), handler());
    }
  }
  return {
    saveProject: saveProject,
    saveProjectAsLocal: saveProjectAsLocal,
    saveCurrentProjectFromShortcut: saveCurrentProjectFromShortcut,
  };
}
