import { VOLCENGINE_VOICE_TYPE_FIELD, VOLCENGINE_SPEAKER_ID_FIELD } from './sharedAudioModelApiFields.js';
import {
  audioSelect,
  audioSlider,
  audioText,
  audioToggle,
  audioSlot,
  createRunningHubAudioCatalogEntry,
  paramMapping,
} from './runningHubAudioCatalogShared.js';
const FORMAT = audioSelect('format', '音频格式', ['mp3', 'wav', 'ogg_opus'], 'mp3'),
  rates = (value) => audioSelect('sampleRate', '采样率', value, '24000'),
  speed = audioSlider('speechRate', '语速', -50, 100, 0),
  volume = audioSlider('loudnessRate', '音量', -50, 100, 0),
  pitch = audioSlider('pitch', '音调', -12, 12, 0),
  VOICE = { ...VOLCENGINE_VOICE_TYPE_FIELD },
  CUSTOM_VOICE = {
    ...VOLCENGINE_SPEAKER_ID_FIELD,
    description: '填写 RunningHub 支持的音色 ID，留空使用预设音色。',
  };
export const runningHubDoubaoAudioEntries = Object.freeze([
  createRunningHubAudioCatalogEntry({
    id: 'doubao-seed-tts-2.0',
    name: '豆包 语音合成 2.0',
    endpoint: '/openapi/v2/bytedance/doubao-seed-tts-2.0',
    docId: 0x1d7ef041,
    order: 210,
    promptMaxLength: 10000,
    promptPlaceholder: '输入要朗读的文本，最多 10000 字符',
    fields: [
      VOICE,
      CUSTOM_VOICE,
      FORMAT,
      rates(['8000', '16000', '22050', '24000', '32000', '44100', '48000']),
      speed,
      volume,
      pitch,
      audioSlider('bitRate', 'MP3 码率', 64000, 160000, 128000, 1000, {
        showWhen: { field: 'format', value: 'mp3' },
      }),
      audioToggle('filterParentheses', '过滤括号内容', true),
      audioSlider('silenceDuration', '末尾静音（毫秒）', 0, 30000, 0, 100),
      audioToggle('filterMarkdown', '过滤 Markdown 标记'),
      audioToggle('filterEmoji', '过滤 Emoji'),
      audioToggle('enableLatex', '朗读数学公式'),
      audioSelect(
        'language',
        '朗读语言',
        [
          'auto',
          'zh-cn',
          'en',
          'ja',
          'es-mx',
          'id',
          'pt-br',
          'pt',
          'ko',
          'de',
          'fr',
          'th',
          'vi',
          'ru',
          'fil',
          'ms',
          'ar',
        ].map((value2) => ({ value: value2, label: value2 === 'auto' ? '自动' : value2 })),
        'auto',
      ),
      audioText('dialect', '方言', '使用支持该方言的音色；中文方言填写拼音。'),
    ],
    mapping: [
      paramMapping('speaker', 'voiceType'),
      paramMapping('format'),
      paramMapping('sample_rate', 'sampleRate'),
      paramMapping('speech_rate', 'speechRate'),
      paramMapping('loudness_rate', 'loudnessRate'),
      paramMapping('pitch'),
      paramMapping('bit_rate', 'bitRate', { when: { field: 'generationParams.format', equals: 'mp3' } }),
      paramMapping('max_length_to_filter_parenthesis', 'filterParentheses', {
        transform: 'parenthesisFilter',
      }),
      paramMapping('silence_duration', 'silenceDuration'),
      paramMapping('disable_markdown_filter', 'filterMarkdown'),
      paramMapping('disable_emoji_filter', 'filterEmoji'),
      paramMapping('enable_latex_tn', 'enableLatex'),
      paramMapping('explicit_language', 'language', {
        when: { field: 'generationParams.language', notEquals: 'auto' },
      }),
      paramMapping('explicit_dialect', 'dialect'),
    ],
    rules: { voiceOverride: { target: 'speaker', custom: 'speakerId', mode: 'voiceMode' } },
  }),
  createRunningHubAudioCatalogEntry({
    id: 'doubao-seed-audio-1.0',
    name: '豆包 音频生成 1.0',
    endpoint: '/openapi/v2/bytedance/doubao-seed-audio-1.0',
    docId: 0x1d7ef042,
    order: 211,
    promptField: 'text_prompt',
    promptMaxLength: 3000,
    promptPlaceholder: '输入声音脚本，可引用 @音频1、@音频2、@音频3，最多 3000 字符',
    slots: [
      audioSlot('audio1', '参考音频1'),
      audioSlot('audio2', '参考音频2'),
      audioSlot('audio3', '参考音频3'),
      { id: 'referenceImage', label: '参考图片', kind: 'image', required: false },
    ],
    fields: [
      audioText('speaker', '音色 ID', '可选。音色 ID、参考音频、参考图片只能选一种。'),
      FORMAT,
      rates(['8000', '16000', '24000', '32000', '44100']),
      speed,
      volume,
      pitch,
    ],
    mapping: [
      paramMapping('speaker'),
      { path: 'audio_url', from: 'inputAudios', omitWhenEmpty: true },
      { path: 'image_url', from: 'inputImages', transform: 'first', omitWhenEmpty: true },
      paramMapping('format'),
      paramMapping('sample_rate', 'sampleRate'),
      paramMapping('speech_rate', 'speechRate'),
      paramMapping('loudness_rate', 'loudnessRate'),
      paramMapping('pitch_rate', 'pitch'),
    ],
    rules: { audioExtensions: ['mp3', 'wav'], exclusiveInputs: ['speaker', 'audio', 'image'] },
  }),
]);
