import test from 'node:test';
import assert from 'node:assert/strict';
import {
  stripImageGenerationResultStateForDerivedNode,
  stripImageGenerationRuntimeState,
} from './imageTaskRuntimeState.js';
import { resolveGenerationUiState } from './generationTaskUiState.js';
(test('imageTaskRuntimeState: 清理图像节点运行态字段但保留业务结果', () => {
  const args = {
      id: 'node_1',
      provider: 'apimart',
      model: 'apimart/nano-banana-2',
      isGenerating: true,
      jobStatus: 'running',
      taskCancellable: true,
      taskResumable: true,
      taskAdapterType: 'workflow',
      generationStartTime: 100,
      generationDuration: 200,
      rhTaskId: 'rh-task',
      rhTaskStatus: 'running',
      rhTaskStartedAt: 1,
      rhTaskRecovering: true,
      rhTaskUseOpenapiQuery: true,
      rhStatusMessage: 'running',
      rhStatusCode: 0x32d,
      dreaminaSubmitId: 'dm-submit',
      dreaminaTaskStatus: 'pending',
      dreaminaTaskPhase: 'generating',
      dreaminaTaskLabel: '生成中',
      dreaminaTaskStartedAt: 2,
      dreaminaTaskLastCheckedAt: 3,
      dreaminaTaskRecovering: true,
      dreaminaTaskLastRaw: { foo: 1 },
      asyncTaskProvider: 'apimart',
      asyncTaskKind: 'image',
      asyncTaskId: 'async-task',
      asyncTaskStatus: 'running',
      asyncTaskStartedAt: 4,
      asyncTaskRecovering: true,
      images: [{ imageUrl: '/output/ok.png', localPath: 'output/ok.png' }],
      prompt: 'cat',
    },
    stripImageGenerationRuntimeState2 = stripImageGenerationRuntimeState({ ...args });
  (assert.equal(stripImageGenerationRuntimeState2.isGenerating, undefined),
    assert.equal(stripImageGenerationRuntimeState2.jobStatus, undefined),
    assert.equal(stripImageGenerationRuntimeState2.taskCancellable, undefined),
    assert.equal(stripImageGenerationRuntimeState2.taskResumable, undefined),
    assert.equal(stripImageGenerationRuntimeState2.taskAdapterType, undefined),
    assert.equal(stripImageGenerationRuntimeState2.generationStartTime, undefined),
    assert.equal(stripImageGenerationRuntimeState2.generationDuration, undefined),
    assert.equal(stripImageGenerationRuntimeState2.rhTaskId, undefined),
    assert.equal(stripImageGenerationRuntimeState2.dreaminaSubmitId, undefined),
    assert.equal(stripImageGenerationRuntimeState2.asyncTaskId, undefined),
    assert.deepEqual(stripImageGenerationRuntimeState2.images, args.images),
    assert.equal(stripImageGenerationRuntimeState2.prompt, 'cat'),
    assert.equal(resolveGenerationUiState(stripImageGenerationRuntimeState2), 'idle'));
}),
  test('imageTaskRuntimeState: 复制清理只移除会触发加载的通用运行态', () => {
    const stripImageGenerationRuntimeState3 = stripImageGenerationRuntimeState({
      id: 'node_done',
      isGenerating: false,
      jobStatus: 'success',
      images: [{ imageUrl: '/output/ok.png' }],
    });
    (assert.equal(stripImageGenerationRuntimeState3.isGenerating, undefined),
      assert.equal(stripImageGenerationRuntimeState3.jobStatus, 'success'),
      assert.deepEqual(stripImageGenerationRuntimeState3.images, [{ imageUrl: '/output/ok.png' }]));
  }),
  test('imageTaskRuntimeState: 派生新生图节点时清理预览上传图片结果但保留配置', () => {
    const args2 = {
        id: 'node_1',
        provider: 'apimart',
        model: 'apimart/nano-banana-2',
        aspectRatio: '自适应',
        imageSize: '4K',
        rhResolution: 0x5a0,
        generationStartTime: 100,
        generationDuration: 200,
        rhTaskId: 'rh-task',
        rhTaskStatus: 'running',
        rhTaskStartedAt: 1,
        rhTaskRecovering: true,
        rhTaskUseOpenapiQuery: true,
        rhStatusMessage: 'running',
        rhStatusCode: 0x32d,
        dreaminaSubmitId: 'dm-submit',
        dreaminaTaskStatus: 'pending',
        dreaminaTaskPhase: 'generating',
        dreaminaTaskLabel: '生成中',
        dreaminaTaskStartedAt: 2,
        dreaminaTaskLastCheckedAt: 3,
        dreaminaTaskRecovering: true,
        dreaminaTaskLastRaw: { foo: 1 },
        asyncTaskProvider: 'apimart',
        asyncTaskKind: 'image',
        asyncTaskId: 'async-task',
        asyncTaskStatus: 'running',
        asyncTaskStartedAt: 4,
        asyncTaskRecovering: true,
        images: [
          {
            imageUrl: '/data/uploads/preview-display.webp',
            sourceUrl: '/data/uploads/preview-original.png',
            localPath: 'data/uploads/preview-original.png',
            originalLocalPath: 'data/uploads/preview-original.png',
            displayLocalPath: 'data/uploads/preview-display.webp',
            thumbLocalPath: 'data/uploads/preview-thumb.webp',
            fileName: 'preview.png',
          },
        ],
        imageUrl: '/data/uploads/preview-display.webp',
        sourceUrl: '/data/uploads/preview-original.png',
        thumbUrl: '/data/uploads/preview-thumb.webp',
        sourceId: 'source-id',
        thumbId: 'thumb-id',
        src: '/data/uploads/preview-display.webp',
        url: '/data/uploads/preview-display.webp',
        resultUrl: '/data/uploads/preview-display.webp',
        localPath: 'data/uploads/preview-original.png',
        originalLocalPath: 'data/uploads/preview-original.png',
        displayLocalPath: 'data/uploads/preview-display.webp',
        thumbLocalPath: 'data/uploads/preview-thumb.webp',
        fileName: 'preview.png',
        isImagesExpanded: true,
        mainImageIndex: 0,
        mask: 'output/mask/mask.png',
        maskPreview: 'output/mask_preview/mask-preview.png',
        maskPreviewUrl: '/output/mask_preview/mask-preview.png',
        maskPolarity: 'paint-white',
        maskSaveToken: 'mask-save-token',
        status: 'success',
        progress: 100,
        error: 'old error',
        prompt: 'cat',
      },
      response = stripImageGenerationResultStateForDerivedNode({ ...args2 });
    (assert.equal(response.images, undefined),
      assert.equal(response.imageUrl, undefined),
      assert.equal(response.sourceUrl, undefined),
      assert.equal(response.thumbUrl, undefined),
      assert.equal(response.sourceId, undefined),
      assert.equal(response.thumbId, undefined),
      assert.equal(response.src, undefined),
      assert.equal(response.url, undefined),
      assert.equal(response.resultUrl, undefined),
      assert.equal(response.localPath, undefined),
      assert.equal(response.originalLocalPath, undefined),
      assert.equal(response.displayLocalPath, undefined),
      assert.equal(response.thumbLocalPath, undefined),
      assert.equal(response.fileName, undefined),
      assert.equal(response.isImagesExpanded, undefined),
      assert.equal(response.mainImageIndex, undefined),
      assert.equal(response.mask, undefined),
      assert.equal(response.maskPreview, undefined),
      assert.equal(response.maskPreviewUrl, undefined),
      assert.equal(response.maskPolarity, undefined),
      assert.equal(response.maskSaveToken, undefined),
      assert.equal(response.generationStartTime, undefined),
      assert.equal(response.generationDuration, undefined),
      assert.equal(response.rhTaskId, undefined),
      assert.equal(response.dreaminaSubmitId, undefined),
      assert.equal(response.asyncTaskId, undefined),
      assert.equal(response.status, undefined),
      assert.equal(response.progress, undefined),
      assert.equal(response.error, undefined),
      assert.equal(response.provider, 'apimart'),
      assert.equal(response.model, 'apimart/nano-banana-2'),
      assert.equal(response.aspectRatio, '自适应'),
      assert.equal(response.imageSize, '4K'),
      assert.equal(response.rhResolution, 0x5a0),
      assert.equal(response.prompt, 'cat'));
  }));
