import test from 'node:test';
import assert from 'node:assert/strict';
import {
  stripImageGenerationResultStateForDerivedNode,
  stripImageGenerationRuntimeState,
} from './imageTaskRuntimeState.js';
import { resolveGenerationUiState } from './generationTaskUiState.js';
(test('imageTaskRuntimeState: 清理图像节点运行态字段但保留业务结果', () => {
  const _0x38406f = {
      id: 'node_1',
      provider: 'apimart',
      model: 'apimart/nano-banana-2',
      isGenerating: true,
      jobStatus: 'running',
      taskCancellable: true,
      taskResumable: true,
      taskAdapterType: 'workflow',
      generationStartTime: 100,
      generationDuration: 200,
      rhTaskId: 'rh-task',
      rhTaskStatus: 'running',
      rhTaskStartedAt: 1,
      rhTaskRecovering: true,
      rhTaskUseOpenapiQuery: true,
      rhStatusMessage: 'running',
      rhStatusCode: 0x32d,
      dreaminaSubmitId: 'dm-submit',
      dreaminaTaskStatus: 'pending',
      dreaminaTaskPhase: 'generating',
      dreaminaTaskLabel: '生成中',
      dreaminaTaskStartedAt: 2,
      dreaminaTaskLastCheckedAt: 3,
      dreaminaTaskRecovering: true,
      dreaminaTaskLastRaw: { foo: 1 },
      asyncTaskProvider: 'apimart',
      asyncTaskKind: 'image',
      asyncTaskId: 'async-task',
      asyncTaskStatus: 'running',
      asyncTaskStartedAt: 4,
      asyncTaskRecovering: true,
      images: [{ imageUrl: '/output/ok.png', localPath: 'output/ok.png' }],
      prompt: 'cat',
    },
    _0x415468 = stripImageGenerationRuntimeState({ ..._0x38406f });
  (assert.equal(_0x415468.isGenerating, undefined),
    assert.equal(_0x415468.jobStatus, undefined),
    assert.equal(_0x415468.taskCancellable, undefined),
    assert.equal(_0x415468.taskResumable, undefined),
    assert.equal(_0x415468.taskAdapterType, undefined),
    assert.equal(_0x415468.generationStartTime, undefined),
    assert.equal(_0x415468.generationDuration, undefined),
    assert.equal(_0x415468.rhTaskId, undefined),
    assert.equal(_0x415468.dreaminaSubmitId, undefined),
    assert.equal(_0x415468.asyncTaskId, undefined),
    assert.deepEqual(_0x415468.images, _0x38406f.images),
    assert.equal(_0x415468.prompt, 'cat'),
    assert.equal(resolveGenerationUiState(_0x415468), 'idle'));
}),
  test('imageTaskRuntimeState: 复制清理只移除会触发加载的通用运行态', () => {
    const _0x24bb07 = stripImageGenerationRuntimeState({
      id: 'node_done',
      isGenerating: false,
      jobStatus: 'success',
      images: [{ imageUrl: '/output/ok.png' }],
    });
    (assert.equal(_0x24bb07.isGenerating, undefined),
      assert.equal(_0x24bb07.jobStatus, 'success'),
      assert.deepEqual(_0x24bb07.images, [{ imageUrl: '/output/ok.png' }]));
  }),
  test('imageTaskRuntimeState: 派生新生图节点时清理预览上传图片结果但保留配置', () => {
    const _0x3e1da8 = {
        id: 'node_1',
        provider: 'apimart',
        model: 'apimart/nano-banana-2',
        aspectRatio: '自适应',
        imageSize: '4K',
        rhResolution: 0x5a0,
        generationStartTime: 100,
        generationDuration: 200,
        rhTaskId: 'rh-task',
        rhTaskStatus: 'running',
        rhTaskStartedAt: 1,
        rhTaskRecovering: true,
        rhTaskUseOpenapiQuery: true,
        rhStatusMessage: 'running',
        rhStatusCode: 0x32d,
        dreaminaSubmitId: 'dm-submit',
        dreaminaTaskStatus: 'pending',
        dreaminaTaskPhase: 'generating',
        dreaminaTaskLabel: '生成中',
        dreaminaTaskStartedAt: 2,
        dreaminaTaskLastCheckedAt: 3,
        dreaminaTaskRecovering: true,
        dreaminaTaskLastRaw: { foo: 1 },
        asyncTaskProvider: 'apimart',
        asyncTaskKind: 'image',
        asyncTaskId: 'async-task',
        asyncTaskStatus: 'running',
        asyncTaskStartedAt: 4,
        asyncTaskRecovering: true,
        images: [
          {
            imageUrl: '/data/uploads/preview-display.webp',
            sourceUrl: '/data/uploads/preview-original.png',
            localPath: 'data/uploads/preview-original.png',
            originalLocalPath: 'data/uploads/preview-original.png',
            displayLocalPath: 'data/uploads/preview-display.webp',
            thumbLocalPath: 'data/uploads/preview-thumb.webp',
            fileName: 'preview.png',
          },
        ],
        imageUrl: '/data/uploads/preview-display.webp',
        sourceUrl: '/data/uploads/preview-original.png',
        thumbUrl: '/data/uploads/preview-thumb.webp',
        sourceId: 'source-id',
        thumbId: 'thumb-id',
        src: '/data/uploads/preview-display.webp',
        url: '/data/uploads/preview-display.webp',
        resultUrl: '/data/uploads/preview-display.webp',
        localPath: 'data/uploads/preview-original.png',
        originalLocalPath: 'data/uploads/preview-original.png',
        displayLocalPath: 'data/uploads/preview-display.webp',
        thumbLocalPath: 'data/uploads/preview-thumb.webp',
        fileName: 'preview.png',
        isImagesExpanded: true,
        mainImageIndex: 0,
        mask: 'output/mask/mask.png',
        maskPreview: 'output/mask_preview/mask-preview.png',
        maskPreviewUrl: '/output/mask_preview/mask-preview.png',
        maskPolarity: 'paint-white',
        maskSaveToken: 'mask-save-token',
        status: 'success',
        progress: 100,
        error: 'old error',
        prompt: 'cat',
      },
      _0x4bdbd2 = stripImageGenerationResultStateForDerivedNode({ ..._0x3e1da8 });
    (assert.equal(_0x4bdbd2.images, undefined),
      assert.equal(_0x4bdbd2.imageUrl, undefined),
      assert.equal(_0x4bdbd2.sourceUrl, undefined),
      assert.equal(_0x4bdbd2.thumbUrl, undefined),
      assert.equal(_0x4bdbd2.sourceId, undefined),
      assert.equal(_0x4bdbd2.thumbId, undefined),
      assert.equal(_0x4bdbd2.src, undefined),
      assert.equal(_0x4bdbd2.url, undefined),
      assert.equal(_0x4bdbd2.resultUrl, undefined),
      assert.equal(_0x4bdbd2.localPath, undefined),
      assert.equal(_0x4bdbd2.originalLocalPath, undefined),
      assert.equal(_0x4bdbd2.displayLocalPath, undefined),
      assert.equal(_0x4bdbd2.thumbLocalPath, undefined),
      assert.equal(_0x4bdbd2.fileName, undefined),
      assert.equal(_0x4bdbd2.isImagesExpanded, undefined),
      assert.equal(_0x4bdbd2.mainImageIndex, undefined),
      assert.equal(_0x4bdbd2.mask, undefined),
      assert.equal(_0x4bdbd2.maskPreview, undefined),
      assert.equal(_0x4bdbd2.maskPreviewUrl, undefined),
      assert.equal(_0x4bdbd2.maskPolarity, undefined),
      assert.equal(_0x4bdbd2.maskSaveToken, undefined),
      assert.equal(_0x4bdbd2.generationStartTime, undefined),
      assert.equal(_0x4bdbd2.generationDuration, undefined),
      assert.equal(_0x4bdbd2.rhTaskId, undefined),
      assert.equal(_0x4bdbd2.dreaminaSubmitId, undefined),
      assert.equal(_0x4bdbd2.asyncTaskId, undefined),
      assert.equal(_0x4bdbd2.status, undefined),
      assert.equal(_0x4bdbd2.progress, undefined),
      assert.equal(_0x4bdbd2.error, undefined),
      assert.equal(_0x4bdbd2.provider, 'apimart'),
      assert.equal(_0x4bdbd2.model, 'apimart/nano-banana-2'),
      assert.equal(_0x4bdbd2.aspectRatio, '自适应'),
      assert.equal(_0x4bdbd2.imageSize, '4K'),
      assert.equal(_0x4bdbd2.rhResolution, 0x5a0),
      assert.equal(_0x4bdbd2.prompt, 'cat'));
  }));
