import {
  shouldDeferRendererDetailsOnMount,
  shouldDeferRendererMediaOnMount,
} from '../../core/rendererDeferredMedia.js';
import { readVideoAudioDefaultEnabledFromStore, resolveVideoMutedPreference } from './videoMuteState.js';
import { createHoverVideoPlaybackLifecycle } from '../shared/hoverVideoPlaybackLifecycle.js';
export function initializeVideoNodeMediaRuntimeState(value, item, key) {
  ((value['_multiStackWrap'] = null),
    (value['_multiLayerEls'] = []),
    (value['_multiErrorEls'] = []),
    (value['_multiToggleBtn'] = null),
    (value['_multiVideosContainer'] = null),
    (value['_cachedVideoUrls'] = new Map()),
    (value['_cachedVideoUrlLoads'] = new Map()),
    (value['_videoObjectUrlLifecycleEpoch'] = 0x0),
    (value['_videoObjectUrlsDisposed'] = ![]),
    (value['_localPlaybackBlobToken'] = 0x0),
    (value['_videoRenderEpoch'] = 0x0),
    (value['_videoSourceAttachToken'] = 0x0),
    (value['_videoSourceAttachTokens'] = new WeakMap()),
    (value['_localPlaybackBlobPromise'] = null),
    (value['_localPlaybackBlobPromiseSource'] = ''),
    (value['_localPlaybackBlobFetchController'] = null),
    (value['_localPlaybackObjectUrl'] = ''),
    (value['_localPlaybackObjectSource'] = ''),
    (value['_lastVideosKeyStr'] = null),
    (value['_lastMainIdx'] = null),
    (value['_lastIsExpanded'] = null),
    (value['_expandPanel'] = null),
    (value['_isMuted'] = resolveVideoMutedPreference(item, {
      videoAudioDefaultEnabled: readVideoAudioDefaultEnabledFromStore(key),
    })),
    (value['_videoClickTimer'] = null),
    (value['_muteBtnEl'] = null),
    (value['_muteIconMutedEl'] = null),
    (value['_muteIconUnmutedEl'] = null),
    (value['_centerIndicatorEl'] = null),
    (value['_centerIndicatorInnerEl'] = null),
    (value['_centerIndicatorTimer'] = null),
    (value['_controlsEl'] = null),
    (value['_playBtnEl'] = null),
    (value['_timeCurrentEl'] = null),
    (value['_timeTotalEl'] = null),
    (value['_progressBarEl'] = null),
    (value['_progressFillEl'] = null),
    (value['_snapBtnEl'] = null),
    (value['_progressRaf'] = 0x0),
    (value['_progressRafVideoEl'] = null),
    (value['_isProgressSeeking'] = ![]),
    (value['_isProgressDragging'] = ![]),
    (value['_progressDragSession'] = null),
    (value['_progressSeekToken'] = 0x0),
    (value['_isManualControl'] = ![]),
    (value['_isHovered'] = ![]),
    (value['_hoverManualPause'] = ![]),
    (value['_isManualLoopPlayback'] = ![]),
    (value['_autoPlayToken'] = 0x0),
    (value['_hoverPlaybackResumeState'] = null),
    (value['_hoverPlaybackLifecycle'] = createHoverVideoPlaybackLifecycle({
      releaseMedia: () => value['_releaseIdlePreviewHoverPlaybackMedia']?.(),
    })),
    (value['_nodeInfoMetaFetchToken'] = 0x0),
    (value['_resultMetaEnrichmentToken'] = 0x0),
    (value['_videoThumbPending'] = new Set()),
    (value['_resultThumbToken'] = 0x0),
    (value['_isExpandedPickClosing'] = ![]),
    (value['_activeFullscreenCleanup'] = null),
    (value['_activeFullscreenVideoEl'] = null),
    (value['_activeFullscreenResultIdentity'] = ''),
    (value['_pendingFullscreenResultIdentity'] = ''),
    (value['_fullscreenOpenEpoch'] = 0x0),
    (value['_rendererDetailsDeferred'] = shouldDeferRendererDetailsOnMount(item)),
    (value['_rendererMediaDeferred'] = shouldDeferRendererMediaOnMount(item)),
    (value['_rendererEagerVideoPreview'] = ![]),
    (value['_rendererThinVideoHydration'] = ![]),
    (value['_renderRefBarPendingWhenVisible'] = ![]),
    (value['_deferredVideoViewRefreshPending'] = ![]),
    (value['_deferredToolbarEl'] = null),
    (value['_deferredToolbarMarkupPending'] = ![]));
}
